//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatBot
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SampleDBEntities : DbContext
    {
        public SampleDBEntities()
            : base("name=SampleDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Error> Error { get; set; }
        public virtual DbSet<Intent> Intent { get; set; }
        public virtual DbSet<Node> Node { get; set; }
        public virtual DbSet<Reference> Reference { get; set; }
    
        public virtual ObjectResult<GetAllConnectedNodes_Result> GetAllConnectedNodes(Nullable<double> previousID)
        {
            var previousIDParameter = previousID.HasValue ?
                new ObjectParameter("PreviousID", previousID) :
                new ObjectParameter("PreviousID", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllConnectedNodes_Result>("GetAllConnectedNodes", previousIDParameter);
        }
    }
}
